version: "3"
services:
  client:
    container_name: amacleanjs/todo-client
    restart: always
    build: "./client"
    ports:
      - "3000:3000"
    links:
      - server
  server:
    container_name: amacleanjs/todo-server
    restart: always
    build: "./server"
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"