version: "3"
services:
  client:
    container_name: todo-client
    restart: always
    build: "./client_v2"
    volumes:
      - ./client_v2:/usr/src/app/client
    ports:
      - "80:3000"
    links:
      - server
  server:
    container_name: todo-server
    restart: always
    build: "./server"
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"